### ISSUE TITLE
Building stgi with Stack fails

### ISSUE THREAD

**Issue by dnovick** [quchen/stgi#100] opened 2017-11-05 16:45 UTC
I heard about stgi in a talk I was listening to this AM and thought I'd take a peek. I tried to build it with Stack and received the following during the stgi-1.0.1: build step:

Configuring stgi-1.0.1...
    Building stgi-1.0.1...
    Preprocessing library stgi-1.0.1...
    [ 1 of 26] Compiling Stg.Util         ( src/Stg/Util.hs, .stack-work/dist/x86_64-linux-nopie/Cabal-1.24.2.0/build/Stg/Util.o )
    [ 2 of 26] Compiling Stg.Language.Prettyprint ( src/Stg/Language/Prettyprint.hs, .stack-work/dist/x86_64-linux-nopie/Cabal-1.24.2.0/build/Stg/Language/Prettyprint.o )
    [ 3 of 26] Compiling Stg.Language     ( src/Stg/Language.hs, .stack-work/dist/x86_64-linux-nopie/Cabal-1.24.2.0/build/Stg/Language.o )
    [ 4 of 26] Compiling Stg.Parser.Parser ( src/Stg/Parser/Parser.hs, .stack-work/dist/x86_64-linux-nopie/Cabal-1.24.2.0/build/Stg/Parser/Parser.o )
    
    /tmp/stack5885/stgi-1.0.1/src/Stg/Parser/Parser.hs:73:18: error:
        • Couldn't match type ‘ErrInfo’ with ‘Doc’
          Expected type: Either Doc ast
            Actual type: Either ErrInfo ast
        • In the expression: Left e
          In a case alternative: Failure e -> Left e
          In the expression:
            case
                parseString (whiteSpace *> p <* eof) mempty (T.unpack input)
            of {
              Success a -> Right a
              Failure e -> Left e }

Is this a known issue?

Dave

**Comment by quchen** [comment] 2017-11-05 19:49
That’s unfortunate, thanks for your report! I’ve had issues with this before, but I thought they were resolved. Trifecta changed its error data type at some point, the fix should be fairly easy. I’ll look into it!

**Comment by quchen** [comment] 2017-11-05 19:55
The build works using the current master commit on my machine. Could you describe the steps you’ve taken from zero to your build error so that I can reproduce it? Thanks! :-)

**Comment by dnovick** [comment] 2017-11-09 11:22
Sorry for the delay. 

I'm just trying to install it as part of my global stack environment. My global project is configured to use the lts-9.12 resolver. 

So, I just enter: stack install stgi.

The install gets through all of the steps except the last one, i.e. the stgi-1.0.1: build step.

Dave

**Comment by quchen** [comment] 2017-11-10 09:48
Hmm, then it sounds like this is a problem with the Hackage release.

For what it’s worth, in order to use STGi, I recommend compiling it yourself, since otherwise you’ll be limited to the one example program the binary ships with. You’ll have to modify the `main` value yourself to evaluate other programs (such as the ones provided for you in the `ExamplePrograms` module). If you need help, feel free to contact me via `dluposchainsky at google` or here!

…meanwhile, I hope I can fix this Hackage issue. :-)

**Comment by quchen** [comment] 2017-11-10 09:58
Ah, this was fixed with ca96c7585257e80771e18fa2874164dcf76c3176 a long time ago, but I haven’t released the new version since then. I’m on it now, it will be STGi 1.1.

**Closed by quchen** 2017-11-10 09:58 UTC
Labels: Bug

**Comment by dnovick** [comment] 2017-11-12 16:42
Thank you! I'l give it a try.
